[gspread]
type = "service_account"
project_id = "projek-karpet"
private_key_id = "860ac7f5c411e1d1dc1d3d9f9afe2bb288f4aef1"


private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDY8sulRxtmkWuf
CmcbXeJAdcwN9g/gCA6EGxWdvAX08EBxD+k3f8Izr6wShyG8IkdYLtKjfNnQua9p
jhgDR2MN6EdCziCy7zGnHapwamrZ2XdYPyZY7j8tZ//t6Uqq9a3i36WUSfL6mhZ0
ueZhegf9YSfGlwjAJqIRJY1Tz+uOykAUujd/lrnh/1TS8GjxUS9F4UBAASxvXvS0
X5ItKffMiuXXsKIJDLHmvxnXlqUxnQ0Zexv/HFV8tQ1Blu98bxw4PcO3Ujynx0x0
HfkmQDRMh9aYhc5mjnmb/aQBV90BeniZmNY6PLCrFV3nI0095tu+bQwpSFRPW91D
Fm7gleJTAgMBAAECggEACQ2ct5bE4HNaETF0cF0Vwh3dot7X9mqE/I31dCHIAoV8
vZsYiYMwffVV52dciNwfVmE3KLEJlTRidbOtxy6VRhvMJCVePPP5V6FydC16AaxE
Vto6cJnvPfxUiZTjfkiGoJc3nX1hK9mpQpFiuUJH5L1x/6Sxg0nkF8tq3zVSfaCu
7xyogRAEvhSWks0Cz3IPwZwI9nrfJpAmf4n7GwMflK2YC+/mEVz3hHkPlSa9hvqe
36cFr64eyMG05Nb3X97Nbh7gSyzY/bsT1CscT4L6L8vg64nIGwOEKSo2d+uV/GfU
qIDvTqLMQisFPKXA3JEhbMXEb5WDBl3OZBSeK+YI3QKBgQD/kIghfK1QRoDsefDB
wPnyDNIRo7Jv+qMJLhSdUudTtYmuh7t/vqi7HiAfTzuK9nyfIeUeAnJy8nzucS/z
ItazKk1HlfkLOcT8ziZl7lQeFPyQyNbuWj+9o+Ofm0sU5ykmI2b7djobF0Rh7qF8
DnOcCupquQUFX4mHKs0IWSpEjQKBgQDZUWu0t55HomPHDqqpuGUq8BixKPPE2wS9
m68aQ8/qrDK+kmCAO2j7sCaoM2yHI1IuEf4tKWEP13opZyd0BsSEnQU+FFrgx6Gn
+ZBgCPuDblBPpdZhKsfocmFJW+tvYS4KtjKfAaf7gNG199JRhaHFuXuvJnljMtQ3
LxRJOni6XwKBgCSG7N4UatUZbp3eA+o9gbv11ySMSBm3MgxC2NFvov6U6NvYLJVi
k81CzgaLlZAUENXRy2SRpvgE7pRJ+zd+GD+9YRRFPDY9iIk1kclp2f3+s+ahvg6N
OaUKQqNyV7XiIECCONriGAX9Olng+JW5nw6DhOPCFBSjhg2asXlq/R6VAoGBAMQX
tBhdl3UMEvyLP3Pl72PPQniZe10mRCDTWi1ZA0O+HgvYCTusYA675CXiQQuv03e+
xJv7upmQ1aqGahNICAuhpBlgRKCPgk8P4jbF5C20XMOB4O/MqpYUn7SSPN9D0UfZ
H9RaqjlHA/Quqpjk/BRuSizBisb4FoW09ZkeKdIBAoGAcxjsbTEegbqynBuTM9js
M8Y43rVWkHta/S6xxcRTn9Zux4IBYxeN43SsRDHy97Ob4W5RhEIxPkd7EtwkOYLa
jKXA4H/ET7o060nqTt0NHZfc693Zywtaem3csdRu5CFWafLBFr/8B8kVe7Do88h0
ZHMvDe6CeI/FjmMSEG8WWyk=
-----END PRIVATE KEY-----"""

client_email = "aplikasi-cuci-karpet@projek-karpet.iam.gserviceaccount.com"
client_id = "108822485802554535875"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/aplikasi-cuci-karpet%40projek-karpet.iam.gserviceaccount.com"






#=======================================================

#========================================================
[gcp_service_account] 
type = "service_account"
project_id = "mycarpetpro-finance"
private_key_id = "f1efc8262e3d8108f3622e557c8d631d39e22f9e"


private_key = """-----BEGIN PRIVATE KEY-----
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/ck970DmMEYWv
  eBRq3WkF592zXF4L4IywqWoTkN5zOra2PAiikr3ncOh5FhmJJPiDo6xnEZpswEID
  SZnwLRC23mTh6U/TobSRHDZ8DBxoN0VeLdr8iWHgyXEWjTm5tQxsjks5GQp8FjqF
  wE8+0hjoeNKQjLGzSmvEEMp3QPB4UkoACf3S/bNE8uQNxA5sVdzJZ+18bS/MQY7n
  FIRBfNpjgKoLjG3+8krSYDHchjxlP9whRtYVsJChRtHeQpcezBMgQZGsIheCshi0
  8ueA581TxRJ4W+4as8BqHjEsF75BPrA3oKk7TiTzQkM7rIRJqFGaPeGpVExUVA87
  SYibZ99lAgMBAAECggEACa5cDsYJFEhHjcfBT+UfPDf32gEr//xB3mYhcdiufb5k
  l8MMlGdeGI/OWwnZzo8IInoFTBdTteJOrvAKy4kv3PDSl6pOydmAciJug+fbNjmY
  oFT/y6uef47tkScg7z8/SqxdvpxW+iQ9Sd8KHYJjgDqp5TrkJThNyktSEw/oM8wD
  pNll2LygQxr8HiRb6ShRSLUBPKMUu0z3V64OZg4dHGLviuAvgWI3pj5VnvObsFOd
  3tyzqAtK9w1ohGLSNgRgLw3TFNYhF0Wp2zt1A3fW0UD2dMWYYCM9zAB+hPqVzBe+
  +hCMe/ZIWOB+beYaW5B0WAwtQqkeVMTIjp5WoZuhKQKBgQD1hreF2yf4Tz2nQqxo
  D/+eVdqHwsS5vB9M9Cf/sTYCdFf6mCTmpLWuT1GRxicfAjv7bymFZpeYWPV3OpBn
  e2rEuhFHqtqUu6hHXbuN5RnbmYCGg+u7DZVVMMG/MSzB9cJNVrvncvdknC/3zjJU
  RhYeR4/XdtinKtnOa1pw6/1oSQKBgQDHnQNXMux/qXdfMlixg9mWDZCvRZjUOOeL
  w/3pVDXjVZ2ngKkF9b3frIvEnzvi28xKVNjeBNaTfQDC/tiW1q8iru2VQy+pCOjc
  wwizPTpeiNCnp7qbs6O2SDO6e+/CiIHIGtUmRBrpyIAVLvT7i2QDsA5PSyPp3kas
  NGt9rhHWPQKBgQDH26BaGnofu0kBdNloX9WAqnwXVKjUU9jayEgi77p6JwBSoTQw
  dtTZDgHk+npv2F7BHcybpVYzEf7FzessAR95Acj9IIuK1HJ3nUoFh/8TbZFcbdge
  TEFJtkWP/1Rikk1WrQqJrWDKCgVV3wfC58YrYa8qAbj74nqnd2WIU+DT2QKBgEbh
  0pXcV27d1q3PSv9+On22Q3J53FNAAbj31+pLJPedJ2aboWmkYdBTjS48/R8JvfmH
  N5tfTHMDKIoVxQOLKJXAWE1wljQIHeiGuUgsrdVz7+QZA4LWv4OzD+tgpzsFDlDo
  dlgoRwZNVG4xRn0sek907R/rJs2dSKtN0f3HGj5hAoGBALb4KOyjVhAJgDrYpo5i
  jb4n19usrcb6FW4plboZ7ig1nm+3EoCDSj0kTIKEQr8S+cKTKckBM+0uYRH+caC7
  STo46JvXNf4gpMqsVTETMBliGAeTJacGUvBWmHQooHTXKu0YLdoOOtx+wr9RAAFY
  mPbopP84g7FIUhmoY7aZ7E6p  -----END PRIVATE KEY-----"""

client_email = "streamlit-finance-helper@mycarpetpro-finance.iam.gserviceaccount.com"
client_id = "101320915917268836046"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-finance-helper%40mycarpetpro-finance.iam.gserviceaccount.com"




