[gspread]
type = "service_account"
project_id = "projek-karpet"
private_key_id = "860ac7f5c411e1d1dc1d3d9f9afe2bb288f4aef1"


private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDY8sulRxtmkWuf
CmcbXeJAdcwN9g/gCA6EGxWdvAX08EBxD+k3f8Izr6wShyG8IkdYLtKjfNnQua9p
jhgDR2MN6EdCziCy7zGnHapwamrZ2XdYPyZY7j8tZ//t6Uqq9a3i36WUSfL6mhZ0
ueZhegf9YSfGlwjAJqIRJY1Tz+uOykAUujd/lrnh/1TS8GjxUS9F4UBAASxvXvS0
X5ItKffMiuXXsKIJDLHmvxnXlqUxnQ0Zexv/HFV8tQ1Blu98bxw4PcO3Ujynx0x0
HfkmQDRMh9aYhc5mjnmb/aQBV90BeniZmNY6PLCrFV3nI0095tu+bQwpSFRPW91D
Fm7gleJTAgMBAAECggEACQ2ct5bE4HNaETF0cF0Vwh3dot7X9mqE/I31dCHIAoV8
vZsYiYMwffVV52dciNwfVmE3KLEJlTRidbOtxy6VRhvMJCVePPP5V6FydC16AaxE
Vto6cJnvPfxUiZTjfkiGoJc3nX1hK9mpQpFiuUJH5L1x/6Sxg0nkF8tq3zVSfaCu
7xyogRAEvhSWks0Cz3IPwZwI9nrfJpAmf4n7GwMflK2YC+/mEVz3hHkPlSa9hvqe
36cFr64eyMG05Nb3X97Nbh7gSyzY/bsT1CscT4L6L8vg64nIGwOEKSo2d+uV/GfU
qIDvTqLMQisFPKXA3JEhbMXEb5WDBl3OZBSeK+YI3QKBgQD/kIghfK1QRoDsefDB
wPnyDNIRo7Jv+qMJLhSdUudTtYmuh7t/vqi7HiAfTzuK9nyfIeUeAnJy8nzucS/z
ItazKk1HlfkLOcT8ziZl7lQeFPyQyNbuWj+9o+Ofm0sU5ykmI2b7djobF0Rh7qF8
DnOcCupquQUFX4mHKs0IWSpEjQKBgQDZUWu0t55HomPHDqqpuGUq8BixKPPE2wS9
m68aQ8/qrDK+kmCAO2j7sCaoM2yHI1IuEf4tKWEP13opZyd0BsSEnQU+FFrgx6Gn
+ZBgCPuDblBPpdZhKsfocmFJW+tvYS4KtjKfAaf7gNG199JRhaHFuXuvJnljMtQ3
LxRJOni6XwKBgCSG7N4UatUZbp3eA+o9gbv11ySMSBm3MgxC2NFvov6U6NvYLJVi
k81CzgaLlZAUENXRy2SRpvgE7pRJ+zd+GD+9YRRFPDY9iIk1kclp2f3+s+ahvg6N
OaUKQqNyV7XiIECCONriGAX9Olng+JW5nw6DhOPCFBSjhg2asXlq/R6VAoGBAMQX
tBhdl3UMEvyLP3Pl72PPQniZe10mRCDTWi1ZA0O+HgvYCTusYA675CXiQQuv03e+
xJv7upmQ1aqGahNICAuhpBlgRKCPgk8P4jbF5C20XMOB4O/MqpYUn7SSPN9D0UfZ
H9RaqjlHA/Quqpjk/BRuSizBisb4FoW09ZkeKdIBAoGAcxjsbTEegbqynBuTM9js
M8Y43rVWkHta/S6xxcRTn9Zux4IBYxeN43SsRDHy97Ob4W5RhEIxPkd7EtwkOYLa
jKXA4H/ET7o060nqTt0NHZfc693Zywtaem3csdRu5CFWafLBFr/8B8kVe7Do88h0
ZHMvDe6CeI/FjmMSEG8WWyk=
-----END PRIVATE KEY-----"""

client_email = "aplikasi-cuci-karpet@projek-karpet.iam.gserviceaccount.com"
client_id = "108822485802554535875"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/aplikasi-cuci-karpet%40projek-karpet.iam.gserviceaccount.com"



# -----------------------------------------------------------
# TAMPAL KOD KUNCI KEWANGAN BAHARU DI SINI (DI BAWAH SEKALI)
# -----------------------------------------------------------
[gcp_service_account]
type = "service_account"
project_id = "mycarpetpro-finance"
private_key_id = "4d556a2151dc837377132500737a741b3b1932a6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC3DZrLOpY/L9Nu
lIASyLM0utAt77MrUL67D51+hBjxcSKvvUuvCGmlE+m7Ok9uTMbOur1v37ZEfbNl
lVcGOWL8Yf+6ILlIl1O5aS5QidpPc1nGkygDF1NthqhkUXF0OMU73ca/E+Io/qUL
9OECtbcVDwbbyTNM5ZwW1xdzg2ckfwc13fUbuvBm8dYLZuRAzp5CfKhRtHVqeorq
2NUcP0s7yX6VD0TWf+NQ0lXIkHqFmSYAMyCzJOo7NJlw4wKeRzcYslB6RquyVWwb
lWEUdKc/NB515qJwiq6dyez5SiQGdUA2RsY8+4P6IETDrHBakpSbNd9RmzR+k1ce
B0kvnq55AgMBAAECggEAEh3AkhhsQjijfjAoNLO0OKW8cK9mVgUZuz2iYqEELvD5
c9cSJHJ6siG0Yhk1Pz9N9au5j9beHQ0rsgQDptQLHds9CdivPaXsXU8xjDr4ZiCO
Y/6wWQ337cED7Vm6Frx/mJssTkDTgycggnxrwG7nfagND7dr4lJfDkufQIlirdPR
rRc8pMmoUrvCtbJFlroZKIf+b5vPGJRXAulKESum39FfoV16ZL2kkMLzGizknvdd
KXs++J9bAQMB6pN8DLvivyKKvpzNzrajmjAl15rhCZFhtER6uAY+R9qH2YE0laZc
rr1UoJN8tczidQ8L4sSaQ3PZgf6js5DjOdM1iv6cAQKBgQDgF2Ib9z2SxpUPFAFV
ZfwghSADV1jtqnki0A6vrqCQlpBzGM9sOyRqXYnt/Ivotz1Sa686QAjL8eK7yknC
l9EVEzj/Yeqgx1k0/w7ofb8dygOZGxX9MJmvT79lphRXPqjU0vTinT5YGtgRater
Xt/4VEU/ze9TqWqzD8YHdo7XuQKBgQDRHko0tgqzu9R4meTWGPWz3f9M0YlJh9Kw
1lZh9NqkZ8xeBtKuwqrpqNy82VvYTezVNFni+0RkXrY9a6eXo6HOitSTR5VBzLve
CQmCTtiPhLlZ87aOftFo18IS95lWu4aLjTxxUtj8dTQjzFa+wRsBoggHuGWiYjMv
/KJggExswQKBgQDPcxYyCXoI7KmFIeHyKs1zVYpDTZNXwZ8OqUlPPfwKnjfvNSKg
cUfO5/UOSeNDdo7gRCwdYrZCBxT8/9G0wVKfjgIP+Zd5a9KbixtEA1TvwNn/3OFI
WLuNXegzs8HU2n71Nq3ZM/RJH+CyjxRE4zm37FuHK5/I9Wd/iLSsqAaokQKBgQCW
3CIuerGnzjZOtr72kVUX6GxYT8WZ7Ula15XD3y+ocVVm88cj2j4QiQiNmMUAe98C
RF0gOaKyQf14u+RQqfR+G3uVsIuFx5w0ZxKcFiN3DgnlUcN+cxDBcP2KT2Moxeof
XMmg+2KcZjUyKiTeQlMoT2s5npZ7mhpRYREHSydXQQKBgQCfbukKxLDaggac9uAA
N6CXgJ64Z3MHnr1/ts1MeUiWsjbCmyQqv6JL27mE+MS3tz9IQ+XQnpV4EfZw3t9w
lg32BmTPAeHBM6WCmEv9Ins/IdtGZcaswfhxCdEmWepqd5xNDyLHMbmWklnBfXYO
8aefkihjAuKsXNsDQmFzxuXXGg==
-----END PRIVATE KEY-----"""
client_email = "streamlit-finance-helper@mycarpetpro-finance.iam.gserviceaccount.com"
client_id = "101320915917268836046"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-finance-helper%40mycarpetpro-finance.iam.gserviceaccount.com"

